name: Evergreen Auto Checkin

on:
  schedule:
    - cron: '5 15 * * *' # í•œêµ­ ì‹œê°„ ì˜¤ì „ 12ì‹œ 05ë¶„ (UTC 15:05)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # workflow ê¶Œí•œ í•„ìš” ì—†ìŒ

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install selenium webdriver-manager

      - name: Run script
        env:
          USER_ID: ${{ secrets.USER_ID }}
          USER_PW: ${{ secrets.USER_PW }}
        run: python run.py

      - name: Commit and Push changes
        env:
          MY_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # ë³€ê²½ëœ ëª¨ë“  íŒŒì¼ ì»¤ë°‹ (ì›Œí¬í”Œë¡œìš° íŒŒì¼ ì œì™¸)
          git add . ':!./.github/workflows/*'
          git commit -m "ğŸ“ ì¶œì„ ê¸°ë¡ ì—…ë°ì´íŠ¸" || echo "No changes"
          
          git push https://x-access-token:${MY_TOKEN}@github.com/${{ github.repository }}.git main

