name: Evergreen Auto Checkin

on:
  schedule:
    - cron: '30 3 * * *' # í•œêµ­ ì‹œê°„ ì˜¤ì „ 12ì‹œ 30ë¶„
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install selenium webdriver-manager

      - name: Run script
        env:
          USER_ID: ${{ secrets.USER_ID }}
          USER_PW: ${{ secrets.USER_PW }}
        run: python run.py

      - name: Commit and Push changes
        env:
          MY_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # ì„¤ì • íŒŒì¼(.github/)ì€ ì œì™¸í•˜ê³  README.md ë“±ë§Œ ì»¤ë°‹
          git add . ':!./.github/workflows/*'
          git commit -m "ğŸ“ ì¶œì„ ê¸°ë¡ ì—…ë°ì´íŠ¸" || echo "No changes"
          
          # ì›ê²© main ìµœì‹  ìƒíƒœë¡œ ë™ê¸°í™” í›„ ì•ˆì „í•˜ê²Œ í‘¸ì‹œ
          git fetch origin main
          git reset --soft origin/main
          git push https://x-access-token:${MY_TOKEN}@github.com/${{ github.repository }}.git main
