name: Evergreen Auto Checkin

on:
  schedule:
    - cron: '30 3 * * *' # í•œêµ­ ì‹œê°„ ì˜¤ì „ 12ì‹œ 30ë¶„
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install selenium webdriver-manager

      - name: Run script
        env:
          USER_ID: ${{ secrets.USER_ID }}
          USER_PW: ${{ secrets.USER_PW }}
        run: python run.py

      - name: Commit and Push README updates
        env:
          MY_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
          # README.mdë§Œ ì»¤ë°‹, ì›Œí¬í”Œë¡œìš° íŒŒì¼ ì œì™¸
          git add README.md ':!./.github/workflows/*'
          git commit -m "ğŸ“ ì¶œì„ ê¸°ë¡ ì—…ë°ì´íŠ¸" || echo "No changes"
      
          # 1. ì›ê²© main ìµœì‹  ê°€ì ¸ì˜¤ê¸°
          git fetch origin main
      
          # 2. ë¡œì»¬ main ê°•ì œ ë™ê¸°í™”
          git reset --hard origin/main
      
          # 3. README.md ì»¤ë°‹ ë‹¤ì‹œ ì ìš©
          git add README.md
          git commit -m "ğŸ“ ì¶œì„ ê¸°ë¡ ì—…ë°ì´íŠ¸" || echo "No changes"
      
          # 4. ê°•ì œ í‘¸ì‹œ
          git push https://x-access-token:${MY_TOKEN}@github.com/${{ github.repository }}.git main --force

